kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  #image: cimg/go:1.19.0
  image: golang:1.19
  commands:
  - make test

- name: publish
  image: plugins/ecr
  when:
    event: tag
  settings:
    repo: cleaner-controller
    registry: 558830342743.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
    dockerfile: Dockerfile
    create_repository: true
    access_key:
      from_secret: 558830342743_AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: 558830342743_AWS_SECRET_ACCESS_KEY
    tags:
      - ${DRONE_TAG##v}
    build_args:
      - "TARGETARCH=amd64"
trigger:
  event:
  - pull_request
  - tag