kind: pipeline
type: kubernetes
name: default

steps:
- name: helmify
  image: golang:1.19
  when:
    event: tag
  commands:
  - make helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - helm package ./cleaner --app-version ${DRONE_TAG##v} --version ${DRONE_TAG##v}
  - mkdir -p dist
  - mv ./cleaner-${DRONE_TAG##v}.tgz dist/cleaner.tgz
  #- tar -czvf dist/cleaner-chart.tar.gz -C ./cleaner .

- name: publish-helm
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GIT_TOKEN
    files: dist/*
  when:
    event: tag

- name: fail
  image: golang:1.19
  commands:
  - exit 1

- name: test
  #image: cimg/go:1.19.0
  image: golang:1.19
  commands:
  - make test

- name: publish-ecr
  image: plugins/ecr
  when:
    event: tag
  settings:
    repo: cleaner-controller
    registry: 558830342743.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
    dockerfile: Dockerfile
    create_repository: true
    access_key:
      from_secret: 558830342743_AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: 558830342743_AWS_SECRET_ACCESS_KEY
    tags:
      - ${DRONE_TAG##v}
    build_args:
      - "TARGETARCH=amd64"
trigger:
  event:
  - pull_request
  - tag
