apiVersion: v1
kind: ConfigMap
metadata:
  name: cleaner-controller-logs-config
data:
  journey: '{{ .Values.opensearch.journey | default "not-configured" }}'
  search_index: '{{ .Values.opensearch.search_index | default "not-configured" }}'