# permissions for end users to edit conditionalttls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: conditionalttl-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cleaner-controller
    app.kubernetes.io/part-of: cleaner-controller
    app.kubernetes.io/managed-by: kustomize
  name: conditionalttl-editor-role
rules:
- apiGroups:
  - cleaner.vtex.io
  resources:
  - conditionalttls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleaner.vtex.io
  resources:
  - conditionalttls/status
  verbs:
  - get
