---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cleaner.vtex.io
  resources:
  - conditionalttls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleaner.vtex.io
  resources:
  - conditionalttls/finalizers
  verbs:
  - update
- apiGroups:
  - cleaner.vtex.io
  resources:
  - conditionalttls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
